In [28]:
from tensorflow.keras.datasets import mnist

In [29]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [30]:
train_images.shape

(60000, 28, 28)

In [31]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [32]:
len(train_labels)

60000

In [33]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [34]:
test_images.shape

(10000, 28, 28)

In [35]:
len(test_labels)

10000

In [36]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [37]:
from tensorflow import keras
from keras import layers

In [38]:
model = keras.Sequential([
    layers.Dense(512, activation='relu'),
    layers.Dense(10, activation = 'softmax')
])

In [39]:
model.compile(optimizer = 'rmsprop', loss = "sparse_categorical_crossentropy", metrics = ['accuracy'])

In [40]:
# Preparing the image data
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

In [41]:
train_images[0]


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [42]:
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255


In [43]:
model.fit(train_images, train_labels, epochs=8, batch_size=128)

Epoch 1/8
469/469 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8734 - loss: 0.4381
Epoch 2/8
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9660 - loss: 0.1145
Epoch 3/8
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9788 - loss: 0.0729
Epoch 4/8
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9845 - loss: 0.0504
Epoch 5/8
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.9889 - loss: 0.0365
Epoch 6/8
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.9917 - loss: 0.0288
Epoch 7/8
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.9946 - loss: 0.0206
Epoch 8/8
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.9960 - loss: 0.0148


In [44]:
#Using the model to make predictions
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([1.9853847e-09, 5.4980404e-10, 2.1957112e-06, 1.8707384e-05,
       5.8510185e-13, 1.1292405e-08, 7.7769583e-13, 9.9997866e-01,
       1.1464198e-08, 3.5061231e-07], dtype=float32)

In [45]:
predictions[0].argmax()

7

In [46]:
predictions[0][7]

0.99997866

In [47]:
test_labels[0]

7

In [48]:
#Evaluating the model on new data
test_loss, test_acc = model.evaluate(test_images,test_labels)


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9785 - loss: 0.0734


In [49]:
print(f"test accuracy: {test_acc}")

test accuracy: 0.9811999797821045
